[build]
  base = "frontend/ecommerce-app"
  command = "npm install --legacy-peer-deps && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  GENERATE_SOURCEMAP = "false"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200